Sender: LSF System <lsfadmin@lo-s4-004>
Subject: Job 480140: <python main.py results/0196> in cluster <leonhard> Exited

Job <python main.py results/0196> was submitted from host <lo-login-01> by user <leoj> in cluster <leonhard> at Wed Jul  4 15:20:18 2018
Job was executed on host(s) <4*lo-s4-004>, in queue <gpu.4h>, as user <leoj> in cluster <leonhard> at Wed Jul  4 15:20:29 2018
</cluster/home/leoj> was used as the home directory.
</cluster/home/leoj/sandbox> was used as the working directory.
Started at Wed Jul  4 15:20:29 2018
Terminated at Wed Jul  4 15:23:22 2018
Results reported at Wed Jul  4 15:23:22 2018

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python main.py results/0196
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   160.17 sec.
    Max Memory :                                 2864 MB
    Average Memory :                             1459.80 MB
    Total Requested Memory :                     32000.00 MB
    Delta Memory :                               29136.00 MB
    Max Swap :                                   -
    Max Processes :                              3
    Max Threads :                                27
    Run time :                                   197 sec.
    Turnaround time :                            184 sec.

The output (if any) follows:

WARNING:tensorflow:From /cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From /cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py:497: calling conv1d (from tensorflow.python.ops.nn_ops) with data_format=NHWC is deprecated and will be removed in a future version.
Instructions for updating:
`NHWC` for data_format is deprecated, use `NWC` instead
2018-07-04 15:21:18.789393: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-04 15:21:19.308354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:04:00.0
totalMemory: 10.91GiB freeMemory: 10.75GiB
2018-07-04 15:21:19.308391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-07-04 15:21:19.574814: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-04 15:21:19.574860: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-07-04 15:21:19.574867: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-07-04 15:21:19.575531: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10409 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
  0%|          | 0/100 [00:00<?, ?it/s]Loss: 0.0222, Reconstruction: 0.0222, KL: 459768.1649:   0%|          | 0/100 [00:12<?, ?it/s]Loss: 0.0222, Reconstruction: 0.0222, KL: 459768.1649:   1%|1         | 1/100 [00:12<19:53, 12.06s/it]Loss: 0.0019, Reconstruction: 0.0019, KL: 1064117.5483:   1%|1         | 1/100 [00:21<35:56, 21.78s/it]Loss: 0.0019, Reconstruction: 0.0019, KL: 1064117.5483:   2%|2         | 2/100 [00:21<17:47, 10.89s/it]Loss: 0.0008, Reconstruction: 0.0008, KL: 1560975.5244:   2%|2         | 2/100 [00:31<25:39, 15.71s/it]Loss: 0.0008, Reconstruction: 0.0008, KL: 1560975.5244:   3%|3         | 3/100 [00:31<16:55, 10.47s/it]Loss: 0.0005, Reconstruction: 0.0005, KL: 1937424.4717:   3%|3         | 3/100 [00:41<22:09, 13.71s/it]Loss: 0.0005, Reconstruction: 0.0005, KL: 1937424.4717:   4%|4         | 4/100 [00:41<16:26, 10.28s/it]Loss: 0.0003, Reconstruction: 0.0003, KL: 2326936.0723:   4%|4         | 4/100 [00:50<20:17, 12.68s/it]Loss: 0.0003, Reconstruction: 0.0003, KL: 2326936.0723:   5%|5         | 5/100 [00:50<16:03, 10.14s/it]Loss: 0.0003, Reconstruction: 0.0003, KL: 2574254.4238:   5%|5         | 5/100 [01:00<19:06, 12.07s/it]Loss: 0.0003, Reconstruction: 0.0003, KL: 2574254.4238:   6%|6         | 6/100 [01:00<15:45, 10.06s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2678506.5234:   6%|6         | 6/100 [01:09<18:14, 11.64s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2678506.5234:   7%|7         | 7/100 [01:09<15:28,  9.98s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2641656.8281:   7%|7         | 7/100 [01:19<17:35, 11.35s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2641656.8281:   8%|8         | 8/100 [01:19<15:13,  9.93s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2874460.8027:   8%|8         | 8/100 [01:29<17:03, 11.13s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2874460.8027:   9%|9         | 9/100 [01:29<15:00,  9.89s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2859751.4668:   9%|9         | 9/100 [01:38<16:39, 10.98s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2859751.4668:  10%|#         | 10/100 [01:38<14:49,  9.88s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2878335.7324:  10%|#         | 10/100 [01:48<16:15, 10.84s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2878335.7324:  11%|#1        | 11/100 [01:48<14:36,  9.85s/it]Loss: nan, Reconstruction: nan, KL: 150002670763.3320:  11%|#1        | 11/100 [01:58<15:55, 10.73s/it] /cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    num_tests=num_tests, basename="sample", ylim=1.1)
  File "/cluster/home/leoj/sandbox/plot.py", line 23, in plot
    cur_factors, score = waveUtils.matchWaves(cur_orgs, cur_factors)
  File "/cluster/home/leoj/sandbox/waveUtils.py", line 148, in matchWaves
    assert loss < placeholder
AssertionError
