Sender: LSF System <lsfadmin@lo-s4-010>
Subject: Job 480141: <python main.py results/0197> in cluster <leonhard> Exited

Job <python main.py results/0197> was submitted from host <lo-login-01> by user <leoj> in cluster <leonhard> at Wed Jul  4 15:20:34 2018
Job was executed on host(s) <4*lo-s4-010>, in queue <gpu.4h>, as user <leoj> in cluster <leonhard> at Wed Jul  4 15:20:59 2018
</cluster/home/leoj> was used as the home directory.
</cluster/home/leoj/sandbox> was used as the working directory.
Started at Wed Jul  4 15:20:59 2018
Terminated at Wed Jul  4 15:23:57 2018
Results reported at Wed Jul  4 15:23:57 2018

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python main.py results/0197
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   189.11 sec.
    Max Memory :                                 3271 MB
    Average Memory :                             1899.67 MB
    Total Requested Memory :                     32000.00 MB
    Delta Memory :                               28729.00 MB
    Max Swap :                                   -
    Max Processes :                              3
    Max Threads :                                27
    Run time :                                   204 sec.
    Turnaround time :                            203 sec.

The output (if any) follows:

WARNING:tensorflow:From /cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From /cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py:497: calling conv1d (from tensorflow.python.ops.nn_ops) with data_format=NHWC is deprecated and will be removed in a future version.
Instructions for updating:
`NHWC` for data_format is deprecated, use `NWC` instead
2018-07-04 15:21:20.446680: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-04 15:21:20.909263: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:04:00.0
totalMemory: 7.92GiB freeMemory: 7.80GiB
2018-07-04 15:21:20.909299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-07-04 15:21:21.636287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-04 15:21:21.636334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-07-04 15:21:21.636342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-07-04 15:21:21.636915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7540 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:04:00.0, compute capability: 6.1)
  0%|          | 0/100 [00:00<?, ?it/s]Loss: 0.0229, Reconstruction: 0.0229, KL: 429707.5541:   0%|          | 0/100 [00:14<?, ?it/s]Loss: 0.0229, Reconstruction: 0.0229, KL: 429707.5541:   1%|1         | 1/100 [00:14<23:59, 14.54s/it]Loss: 0.0022, Reconstruction: 0.0022, KL: 929833.8784:   1%|1         | 1/100 [00:27<44:41, 27.09s/it]Loss: 0.0022, Reconstruction: 0.0022, KL: 929833.8784:   2%|2         | 2/100 [00:27<22:07, 13.54s/it]Loss: 0.0009, Reconstruction: 0.0009, KL: 1214418.3311:   2%|2         | 2/100 [00:39<32:17, 19.77s/it]Loss: 0.0009, Reconstruction: 0.0009, KL: 1214418.3311:   3%|3         | 3/100 [00:39<21:18, 13.18s/it]Loss: 0.0005, Reconstruction: 0.0005, KL: 1606246.5068:   3%|3         | 3/100 [00:52<28:02, 17.35s/it]Loss: 0.0005, Reconstruction: 0.0005, KL: 1606246.5068:   4%|4         | 4/100 [00:52<20:49, 13.01s/it]Loss: 0.0003, Reconstruction: 0.0003, KL: 1948726.2910:   4%|4         | 4/100 [01:04<25:47, 16.12s/it]Loss: 0.0003, Reconstruction: 0.0003, KL: 1948726.2910:   5%|5         | 5/100 [01:04<20:25, 12.90s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2351279.3594:   5%|5         | 5/100 [01:17<24:23, 15.41s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2351279.3594:   6%|6         | 6/100 [01:17<20:06, 12.84s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2523443.4648:   6%|6         | 6/100 [01:29<23:23, 14.93s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2523443.4648:   7%|7         | 7/100 [01:29<19:49, 12.79s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2838664.9004:   7%|7         | 7/100 [01:41<22:34, 14.57s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 2838664.9004:   8%|8         | 8/100 [01:41<19:32, 12.74s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 3235665.1309:   8%|8         | 8/100 [01:54<21:55, 14.29s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 3235665.1309:   9%|9         | 9/100 [01:54<19:16, 12.71s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 3134382.6973:   9%|9         | 9/100 [02:06<21:23, 14.10s/it]Loss: 0.0002, Reconstruction: 0.0002, KL: 3134382.6973:  10%|#         | 10/100 [02:06<19:02, 12.69s/it]Loss: 0.0001, Reconstruction: 0.0001, KL: 3401414.6016:  10%|#         | 10/100 [02:19<20:54, 13.94s/it]Loss: 0.0001, Reconstruction: 0.0001, KL: 3401414.6016:  11%|#1        | 11/100 [02:19<18:47, 12.67s/it]Loss: nan, Reconstruction: nan, KL: 650003031549.7988:  11%|#1        | 11/100 [02:31<20:28, 13.80s/it] /cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    num_tests=num_tests, basename="sample", ylim=1.1)
  File "/cluster/home/leoj/sandbox/plot.py", line 23, in plot
    cur_factors, score = waveUtils.matchWaves(cur_orgs, cur_factors)
  File "/cluster/home/leoj/sandbox/waveUtils.py", line 148, in matchWaves
    assert loss < placeholder
AssertionError
