Sender: LSF System <lsfadmin@lo-s4-035>
Subject: Job 503060: <python main.py results/0216> in cluster <leonhard> Exited

Job <python main.py results/0216> was submitted from host <lo-login-02> by user <leoj> in cluster <leonhard> at Thu Jul 12 11:18:46 2018
Job was executed on host(s) <4*lo-s4-035>, in queue <gpu.4h>, as user <leoj> in cluster <leonhard> at Thu Jul 12 11:25:27 2018
</cluster/home/leoj> was used as the home directory.
</cluster/home/leoj/sandbox> was used as the working directory.
Started at Thu Jul 12 11:25:27 2018
Terminated at Thu Jul 12 11:28:47 2018
Results reported at Thu Jul 12 11:28:47 2018

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python main.py results/0216
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   279.58 sec.
    Max Memory :                                 1661 MB
    Average Memory :                             1411.14 MB
    Total Requested Memory :                     64000.00 MB
    Delta Memory :                               62339.00 MB
    Max Swap :                                   -
    Max Processes :                              3
    Max Threads :                                27
    Run time :                                   213 sec.
    Turnaround time :                            601 sec.

The output (if any) follows:

WARNING:tensorflow:From /cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From /cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py:497: calling conv1d (from tensorflow.python.ops.nn_ops) with data_format=NHWC is deprecated and will be removed in a future version.
Instructions for updating:
`NHWC` for data_format is deprecated, use `NWC` instead
2018-07-12 11:25:49.884781: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-12 11:25:50.408818: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:04:00.0
totalMemory: 10.91GiB freeMemory: 10.75GiB
2018-07-12 11:25:50.408866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-07-12 11:25:50.710258: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-12 11:25:50.710303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-07-12 11:25:50.710311: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-07-12 11:25:50.710951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10409 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
  0%|          | 0/100 [00:00<?, ?it/s]Loss: -14.9435, Log-proba-loss: -14.9436, KL: 0.5749:   0%|          | 0/100 [00:22<?, ?it/s]Loss: -14.9435, Log-proba-loss: -14.9436, KL: 0.5749:   1%|1         | 1/100 [00:22<37:51, 22.94s/it]Loss: -14.7193, Log-proba-loss: -14.7194, KL: 1.2983:   1%|1         | 1/100 [00:43<1:11:20, 43.24s/it]Loss: -14.7193, Log-proba-loss: -14.7194, KL: 1.2983:   2%|2         | 2/100 [00:43<35:18, 21.62s/it]  Loss: -14.4807, Log-proba-loss: -14.4815, KL: 7.7929:   2%|2         | 2/100 [01:03<51:43, 31.67s/it]Loss: -14.4807, Log-proba-loss: -14.4815, KL: 7.7929:   3%|3         | 3/100 [01:03<34:08, 21.11s/it]Loss: -13.9251, Log-proba-loss: -13.9598, KL: 346.5973:   3%|3         | 3/100 [01:23<44:58, 27.82s/it]Loss: -13.9251, Log-proba-loss: -13.9598, KL: 346.5973:   4%|4         | 4/100 [01:23<33:22, 20.86s/it]Loss: -13.6719, Log-proba-loss: -13.7186, KL: 466.6450:   4%|4         | 4/100 [01:43<41:27, 25.91s/it]Loss: -13.6719, Log-proba-loss: -13.7186, KL: 466.6450:   5%|5         | 5/100 [01:43<32:48, 20.73s/it]Loss: -13.4207, Log-proba-loss: -13.5225, KL: 1018.3004:   5%|5         | 5/100 [02:03<39:12, 24.77s/it]Loss: -13.4207, Log-proba-loss: -13.5225, KL: 1018.3004:   6%|6         | 6/100 [02:03<32:20, 20.64s/it]Loss: -13.2316, Log-proba-loss: -13.3815, KL: 1499.2722:   6%|6         | 6/100 [02:23<37:33, 23.97s/it]Loss: -13.2316, Log-proba-loss: -13.3815, KL: 1499.2722:   7%|7         | 7/100 [02:23<31:51, 20.55s/it]Loss: 49.5310, Log-proba-loss: -13.2469, KL: 627778.7671:   7%|7         | 7/100 [02:43<36:18, 23.42s/it]Loss: 49.5310, Log-proba-loss: -13.2469, KL: 627778.7671:   8%|8         | 8/100 [02:43<31:25, 20.50s/it]2018-07-12 11:28:45.773453: E tensorflow/core/kernels/check_numerics_op.cc:185] abnormal_detected_host @0x2af23a005e00 = {1, 0} vae/shared_encoder/conv-02/weights/read:0
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    x, x_org, nan = vae.train()
  File "/cluster/home/leoj/sandbox/vae.py", line 253, in train
    loss, recon_loss, kl_loss, loss_labels = self.update(x, kl_loss_mult, learning_rate[epoch])
  File "/cluster/home/leoj/sandbox/vae.py", line 207, in update
    self._learning_rate: learning_rate})
  File "/cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: vae/shared_encoder/conv-02/weights/read:0 : Tensor had NaN values
	 [[Node: vae/CheckNumerics_25 = CheckNumerics[T=DT_FLOAT, message="vae/shared_encoder/conv-02/weights/read:0", _device="/job:localhost/replica:0/task:0/device:GPU:0"](vae/shared_encoder/conv-02/weights/read, ^vae/CheckNumerics_24)]]

Caused by op u'vae/CheckNumerics_25', defined at:
  File "main.py", line 9, in <module>
    vae = VAE(latent_dim=config.latent_dim, batch_size=config.batch_size, config=config)
  File "/cluster/home/leoj/sandbox/vae.py", line 23, in __init__
    self._build_graph()
  File "/cluster/home/leoj/sandbox/vae.py", line 123, in _build_graph
    self.check = tf.add_check_numerics_ops()
  File "/cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/python/ops/numerics.py", line 99, in add_check_numerics_ops
    check_op = [array_ops.check_numerics(output, message=message)]
  File "/cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 734, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): vae/shared_encoder/conv-02/weights/read:0 : Tensor had NaN values
	 [[Node: vae/CheckNumerics_25 = CheckNumerics[T=DT_FLOAT, message="vae/shared_encoder/conv-02/weights/read:0", _device="/job:localhost/replica:0/task:0/device:GPU:0"](vae/shared_encoder/conv-02/weights/read, ^vae/CheckNumerics_24)]]

