Sender: LSF System <lsfadmin@lo-s4-034>
Subject: Job 395152: <python myMain.py> in cluster <leonhard> Exited

Job <python myMain.py> was submitted from host <lo-login-02> by user <leoj> in cluster <leonhard> at Sun May  6 13:24:08 2018.
Job was executed on host(s) <4*lo-s4-034>, in queue <gpu.4h>, as user <leoj> in cluster <leonhard> at Sun May  6 13:24:11 2018.
</cluster/home/leoj> was used as the home directory.
</cluster/home/leoj/sandbox> was used as the working directory.
Started at Sun May  6 13:24:11 2018.
Terminated at Sun May  6 13:24:17 2018.
Results reported at Sun May  6 13:24:17 2018.

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python myMain.py
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   2.87 sec.
    Max Memory :                                 203 MB
    Average Memory :                             94.00 MB
    Total Requested Memory :                     16000.00 MB
    Delta Memory :                               15797.00 MB
    Max Swap :                                   -
    Max Processes :                              3
    Max Threads :                                4
    Run time :                                   18 sec.
    Turnaround time :                            9 sec.

The output (if any) follows:

WARNING:tensorflow:From /cluster/home/leoj/.virtualenvs/mp/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
('originals.shape =', (4950, 2, 2048, 1))
Traceback (most recent call last):
  File "myMain.py", line 26, in <module>
    encoder=nets.fc_1d_encoder, decoder=nets.fc_1d_decoder)
  File "/cluster/home/leoj/sandbox/vae.py", line 31, in __init__
    self._build_graph()
  File "/cluster/home/leoj/sandbox/vae.py", line 51, in _build_graph
    self.shared_encoded = networks.fc_1d_encoder_shared(self.x)
  File "/cluster/home/leoj/sandbox/networks.py", line 12, in fc_1d_encoder_shared
    e = layers.conv2d(e, config.conv_channel_num(), config.conv_filter_size(i), stride=2, padding='same',
TypeError: conv_channel_num() takes exactly 1 argument (0 given)
